const CONFIG = {
  introTitle: "HELLO",
  introDesc: `Hi hê lô mô tô chào em`,
  btnIntro: "hihi-haha",
  title: "Thương Thương 😙",
  desc: "I Love You ",
  btnYes: " Thích anh rồi đúng không ? <33",
  btnNo: "Không, Anh trai à :3",
  question: "Thế giới có hơn 7 tỉ người mà sao em lại thích anh <3",
  btnReply: "Gửi cho anh <3",
  reply: "Yêu thì yêu mà không yêu thì yêu <33333333",
  mess: "Anh biết mà 🥰. Yêu em nhiều  😘😘",
  messDesc: "Tối anh chở đi chơi nhé.",
  btnAccept: "Tới công chuyện luôn  <3",
  messLink: "https://m.me/Nguyentiendungtpm6dtu",
};
